// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZCJy0-rOoxV6NGDUh46c_mgNqrrXpzk',
    appId: '1:788136656043:web:41abda08a1a0e750c38bee',
    messagingSenderId: '788136656043',
    projectId: 'flutterbankapp-db6b9',
    authDomain: 'flutterbankapp-db6b9.firebaseapp.com',
    storageBucket: 'flutterbankapp-db6b9.firebasestorage.app',
    measurementId: 'G-SZXHRP8Z3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KUyGSMTVSI6bZF2RRtLEigrPniDTwgg',
    appId: '1:788136656043:android:3fb29f7089ba6315c38bee',
    messagingSenderId: '788136656043',
    projectId: 'flutterbankapp-db6b9',
    storageBucket: 'flutterbankapp-db6b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9J8fbGC-gMrYnqiwfAzyYuF6nJhe82x4',
    appId: '1:788136656043:ios:ffd23084ee6cf357c38bee',
    messagingSenderId: '788136656043',
    projectId: 'flutterbankapp-db6b9',
    storageBucket: 'flutterbankapp-db6b9.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9J8fbGC-gMrYnqiwfAzyYuF6nJhe82x4',
    appId: '1:788136656043:ios:ffd23084ee6cf357c38bee',
    messagingSenderId: '788136656043',
    projectId: 'flutterbankapp-db6b9',
    storageBucket: 'flutterbankapp-db6b9.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEZCJy0-rOoxV6NGDUh46c_mgNqrrXpzk',
    appId: '1:788136656043:web:a922964cb1102469c38bee',
    messagingSenderId: '788136656043',
    projectId: 'flutterbankapp-db6b9',
    authDomain: 'flutterbankapp-db6b9.firebaseapp.com',
    storageBucket: 'flutterbankapp-db6b9.firebasestorage.app',
    measurementId: 'G-57CF7FTVR8',
  );
}
